
/*
 * Copyright 2023. CodeThink Technologies and contributors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package cn.codethink.xiaoming.expression.acl;

/** CUP generated class containing symbol constants. */
@SuppressWarnings("all")
public class sym {
  /* terminals */
  public static final int LBRACE = 4;
  public static final int NULL_LITERAL = 15;
  public static final int BOOLEAN_LITERAL = 12;
  public static final int STRING_LITERAL = 14;
  public static final int CHARACTER_LITERAL = 13;
  public static final int EOF = 0;
  public static final int FLOATING_POINT_LITERAL = 11;
  public static final int RBRACK = 7;
  public static final int COMMA = 8;
  public static final int error = 1;
  public static final int RPAREN = 3;
  public static final int IDENTIFIER = 9;
  public static final int LBRACK = 6;
  public static final int LPAREN = 2;
  public static final int RBRACE = 5;
  public static final int INTEGER_LITERAL = 10;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "LBRACK",
  "RBRACK",
  "COMMA",
  "IDENTIFIER",
  "INTEGER_LITERAL",
  "FLOATING_POINT_LITERAL",
  "BOOLEAN_LITERAL",
  "CHARACTER_LITERAL",
  "STRING_LITERAL",
  "NULL_LITERAL"
  };
}

